### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fanyeren**
add Process.wait to example script, fix the zombie process problem

### CODE REVIEW

**Comment by ranjib** [comment]
you can pass attach(wait: true)  directly. http://www.rubydoc.info/gems/ruby-lxc/LXC/Container#attach-instance_method

**Comment by andrenth** [comment]
Yeah, `wait: true` would be the best for this example. It was really a mistake to leave this flag as false by default :(

**Comment by fanyeren** [comment]
you guys are right, it works！

**Comment by andrenth** [comment]
If you want, make a pull request for README to add wait: true to the attach
call. This issue has come up more than once...

**Pull request closed without merging**
